settings:
  log_mode: text
  log_level: INFO
  output_mode: cli
    update_interval: 60
    market_pairs:
    - BAT/BTC
    - ETC/BTC
    - NAV/BTC
    - GTO/BTC
    - SNT/BTC
    - XMR/BTC
    - QKC/BTC
    - QLC/BTC

exchanges:
    binance:
        required:
            enabled: true

indicators:
    rsi:
        - enabled: true
          alert_enabled: false
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 30m
          period_count: 50
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - rsi
          hot: 30
          cold: 70
          candle_period: 30m
          period_count: 14
    stoch_rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 30m
          period_count: 14

notifiers:
    telegram:
        required:
            token: 683852101:AAE2wixjpG1OgMkX7thES4YoUyqc6B5wI-0
            chat_id: 683852101
        optional:
            parse_mode: html
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}" 